services:
  # Users
  evoventa-api:
    build: 
      context: ./
      dockerfile: dockerfile.prod
      args:
        - DATABASE_URL=${DATABASE_URL}
    image: evoventa-api-prod
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - CLIENT_URLS=${CLIENT_URLS}\
      - JWT_SECRET=${JWT_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}


